# Dependabot configuration for claude-flow-on-fly
# This configuration monitors Docker dependencies for the remote development environment

version: 2
updates:
  # Docker base images and system dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Vancouver"
    # Focus on security updates for infrastructure
    open-pull-requests-limit: 5
    reviewers:
      - "cphillipson"
    assignees:
      - "cphillipson"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    commit-message:
      prefix: "docker"
      include: "scope"